# constants for creating arguments

# Credentials
APPNAME = "appname"
PASSWORD = "password"
CIG_USERNAME = "cig-username"
CIG_PASSWD = "cig-passwd"

# Request
LANGUAGE_CODE = "language-code"
REQUEST = "request"
PIECE_CODE = "piece-code"
PIECE_CUSTOMER_REFERENCE = "piece-customer-reference"
TAS_ORDER_NO = "tas-order-no"
D_GET_PIECE = "d-get-piece"
D_GET_PIECE_DETAIL = "d-get-piece-detail"
D_GET_SIGNATURE = "d-get-signature"
GET_STATUS_FOR_PUBLIC_USER = "get-status-for-public-user"
ZIP_CODE = "zip-code"

TEST = "Test"

# Response
# piece-shipment-list
PIECE_SHIPMENT_LIST = "piece-shipment-list"
CODE = "code"
NAME = "name"
REQUEST_ID = "request-id"
ERROR = "error"

# piece-shipment
PIECE_SHIPMENT = "piece-shipment"
AIRWAY_BILL_NUMBER = "airway-bill-number"
DELIVERY_EVENT_FLAG = "delivery-event-flag"
DEST_COUNTRY = "dest-country"
DIVISION = "division"
DOMESTIC_ID = "domestic-id"
ERROR_STATUS = "error-status"
EVENT_COUNTRY = "event-country"
EVENT_LOCATION = "event-location"
ICE = "ice"
IDENTIFIER_TYPE = "identifier-type"
INTERNATIONAL_FLAG = "international-flag"
LEITCODE = "leitcode"
MATCHCODE = "matchcode"
# NAME = "name"
ORDER_PREFERRED_DELIVERY_DAY = "order-preferred-delivery-day"
ORIGIN_COUNTRY = "origin-country"
PAN_RECIPIENT_ADDRESS = "pan-recipient-address"
PAN_RECIPIENT_CITY = "pan-recipient-city"
PAN_RECIPIENT_NAME = "pan-recipient-name"
PAN_RECIPIENT_POSTALCODE = "pan-recipient-postalcode"
PAN_RECIPIENT_STREET = "pan-recipient-street"
# PIECE_CODE = "piece-code"
# PIECE_CUSTOMER_REFERENCE = "piece-customer-reference"
PIECE_ID = "piece-id"
PIECE_IDENTIFIER = "piece-identifier"
PRODUCT_CODE = "product-code"
PRODUCT_KEY = "product-key"
PRODUCT_NAME = "product-name"
PSLZ_NR = "pslz-nr"
RECIPIENT_CITY = "recipient-city"
RECIPIENT_ID = "recipient-id"
RECIPIENT_ID_TEXT = "recipient-id-text"
RECIPIENT_NAME = "recipient-name"
RECIPIENT_STREET = "recipient-street"
RIC = "ric"
ROUTING_CODE_EAN = "routing-code-ean"
RUECKSENDUNG = "ruecksendung"
SEARCHED_PIECE_CODE = "searched-piece-code"
SEARCHED_REF_NO = "searched-ref-no"
SEARCHED_REF_NR = "searched-ref-nr"
SHIPMENT_CODE = "shipment-code"
SHIPMENT_CUSTOMER_REFERENCE = "shipment-customer-reference"
SHIPMENT_HEIGHT = "shipment-height"
SHIPMENT_LENGTH = "shipment-length"
SHIPMENT_WEIGHT = "shipment-weight"
SHIPMENT_WIDTH = "shipment-width"
SHIPPER_ADDRESS = "shipper-address"
SHIPPER_CITY = "shipper-city"
SHIPPER_NAME = "shipper-name"
SHIPPER_STREET = "shipper-street"
SHORT_STATUS = "short-status"
STANDARD_EVENT_CODE = "standard-event-code"
STATUS = "status"
STATUS_LISTE = "status-liste"
STATUS_TIMESTAMP = "status-timestamp"
UPU = "upu"

# piece-event-list
PIECE_EVENT_LIST = "piece-event-list"
_BUILD_TIME = "_build-time"
# LEITCODE = "leitcode"
# NAME = "name"
# ORDER_PREFERRED_DELIVERY_DAY = "order-preferred-delivery-day"
# PIECE_ID = "piece-id"
# PIECE_IDENTIFIER = "piece-identifier"
# PSLZ_NR = "pslz-nr"
# ROUTING_CODE_EAN = "routing-code-ean"
# RUECKSENDUNG = "ruecksendung"

# piece-event
PIECE_EVENT = "piece-event"
# EVENT_COUNTRY = "event-country"
# EVENT_LOCATION = "event-location"
EVENT_STATUS = "event-status"
EVENT_TEXT = "event-text"
EVENT_TIMESTAMP = "event-timestamp"
# ICE = "ice"
# NAME = "name"
# RIC = "ric"
# RUECKSENDUNG = "ruecksendung"
# STANDARD_EVENT_CODE = "standard-event-code"

# signature-list
SIGNATURE_LIST = "signature-list"
# CODE = "code"
# NAME = "name"
# REQUEST_ID = "request-id"

#signature
SIGNATURE = "signature"
EVENT_DATE = "event-date"
IMAGE = "image"
MIME_TYPE = "mime-type"
# NAME = "name="

#credentials
TNT_USER = "tnt_user"
TNT_PASS = "tnt_pass"
CIG_DEVID = "cig_devid"
CIG_PASS = "cig_pass"
ZT_USER = "zt_user"
ZT_PASS = "zt_pass"
APPID = "appid"
TOKEN = "token"

# business customer shipping

# sender
SH_CITY = "Shipper_city"
SH_COMPANY_NAME = "Shipper_company_name"
SH_CONTACT_EMAIL = "Shipper_contact_email"
# SH_CONTACT_NAME = "Shipper_contact_name"
SH_CONTACT_PHONE = "Shipper_contact_phone"
SH_STREET = "Shipper_street"
SH_STREET_NR = "Shipper_street_nr"
SH_ZIP = "Shipper_zip"

# receiver
RC_COMPANY_NAME = "Receiver_company_name"
RC_COMPANY_NAME_2 = "Receiver_company_name_2"
RC_CONTACT_EMAIL = "Receiver_contact_email"
# RC_CONTACT_NAME = "Receiver_contact_name"
RC_CONTACT_PHONE = "Receiver_contact_phone"
# RC_FIRST_NAME = "Receiver_first_name"
# RC_LAST_NAME = "Receiver_last_name"
RC_LOCAL_CITY = "Receiver_local_city"
RC_LOCAL_STREET = "Receiver_local_street"
RC_LOCAL_STREETNR = "Receiver_local_streetnr"
RC_LOCAL_ZIP = "Receiver_local_zip"

# shipment details
NUMBER_OF_SHIPMENTS = "Number_of_shipments"
CUSTOMER_REFERENCE = "Customer_reference"
METHOD = "Method"
SHIPPING_NUMBER = "Shipping_number"

INTRASHIP_USER = "Intraship_user"
INTRASHIP_PASSWORD = "Intraship_password"
EKP = "EKP"
PARTNER_ID = "Partner_ID"

